- name: Update sudo package
  apt:
    name: sudo
    state: latest
    install_recommends: false
    update_cache: true
    force_apt_get: yes
  register: sudo_result
  until: sudo_result is succeeded
  retries: 5
  delay: 10
  failed_when: sudo_result is failure

- name: 'Install pip3'
  apt:
    name: python3-pip
    state: present
    install_recommends: false
    update_cache: true
    force_apt_get: yes
  register: python3_pip_result
  until: python3_pip_result is succeeded
  retries: 5
  delay: 10
  failed_when: python3_pip_result is failure

- name: Upgrade pip3 to latest
  pip:
    name: pip
    state: latest
  become: yes

- name: Install Jupyter
  pip:
    name: jupyterlab
    state: latest
  become: yes
