name: deploy-ai-workshop
on:
  workflow_dispatch:
    inputs:
      gcp_project:
        description: Google Cloud project ID
        required: true
        default: ai-workshop-322714
      name_prefix:
        description: Prefix to identify resources
        required: true
        description: workshop
      source_image:
        description: Image name
        required: true
        default: ai-workshop-image-6122cba1-3417-79c9-970e-84c998b203a5
      environment:
        description: Environment type to deploy
        required: true
        default: development
      build_region:
        description: Google Cloud region
        required: true
        default: 'us-central1'
      build_zone:
        description: Google Cloud zone
        required: true
        default: 'us-central1-a'
      machine_type:
        description: Machine type for compute instances
        required: true
        default: 'n2-standard-1'
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_SA_PACKER_KEY }}
          export_default_credentials: true

      - name: Update apt
        run: sudo apt-get update

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform

      - name: Run Terraform
        run: |
          cd terraform/environments/${{ github.event.inputs.environment }}
          terraform init -backend-config="${{ github.event.inputs.environment }}.tfbackend"
          terraform apply \
            -var gcp_project="${{ github.event.inputs.gcp_project }}" \
            -var "name_prefix="${{ github.event.inputs.name_prefix }}" \
            -var "workshop_image="${{ github.event.inputs.image_name }}"
            -var "source_image="${{ github.event.inputs.source_image }}" \
            -var zone="${{ github.event.inputs.build_zone }}" \
            -var region="${{ github.event.inputs.build_region }}" \
            -var machine_type="${{ github.event.inputs.machine_type }}"

